\documentclass{article}

\title{Read in the data, look at basic statistics, generate Table 1}

\begin{document}

\maketitle

\section{Load all libraries and functions}

<<loadAndSource, echo=TRUE>>=
library(ggplot2)
library(reshape)
library(genefilter)
library(RColorBrewer) 
library(dplyr)
library(xtable)

source("functions.R")
@

\section{Load data, add age categories}

Read in data from csv file:
<<readInData, echo=TRUE>>=
MasterFrame <- read.csv("S1_Table.csv")
@

Take a look at the dataset:
<<nPeaks, echo=TRUE>>=
dim(MasterFrame)
head(colnames(MasterFrame))
tail(colnames(MasterFrame))

MasterFrame[1:5,1:5]
@

Create vector of metabolites and get number of metabolites:
<<vectMetab, echo=TRUE>>=
##metabolite IDs all have the format (from XCMS) of M.mass.T.retentiontime.n/p 
##(for negative or positive mode) 
mets <- colnames(MasterFrame)[grep("M[[:digit:]]+T[[:digit:]]+",colnames(MasterFrame))]
head(mets)
tail(mets)
length(mets)
@

Create age categories:
<<ageGroupsThresh, echo=TRUE>>=
range(MasterFrame$Age)

MasterFrame$Category <- ""

MasterFrame$Category[MasterFrame$Age >= 4 & MasterFrame$Age < 7] <- 
  "4-7 years"
MasterFrame$Category[MasterFrame$Age >= 7 & MasterFrame$Age < 11] <- 
  ">7-11 years"
MasterFrame$Category[MasterFrame$Age >= 11 & MasterFrame$Age < 18] <- 
  ">11-18 years"
MasterFrame$Category[MasterFrame$Age >= 18 & MasterFrame$Age < 29] <- 
  ">18-29 years"

MasterFrame$Category <- factor(MasterFrame$Category, 
                               levels = c("4-7 years", 
                                          ">7-11 years", 
                                          ">11-18 years",
                                          ">18-29 years"))

table(MasterFrame$Category)
@

\section{Get basic statistics}

Get some basic statistics, like number of DMD cases and controls by site, age distribution for each
group:
<<basicStats, echo=TRUE>>=
##number of DMD cases and controls:
table(MasterFrame$Status)

##number of people at each site:
table(MasterFrame$Site)

##number of DMD cases and controls by site:
table(MasterFrame$Status, MasterFrame$Site)

##age distribution in each group:
quantile(MasterFrame$Age[MasterFrame$Status == "DMD"])
quantile(MasterFrame$Age[MasterFrame$Status == "Control"])

table(MasterFrame$Category[MasterFrame$Status == "DMD"])
table(MasterFrame$Category[MasterFrame$Status == "Control"])
@

\section{Table 1}

Generate Table 1 from paper:
<<makeTable1, echo=TRUE>>=
tabBySite <- table(MasterFrame$Site, MasterFrame$Status)
tabBySite <- data.frame(tabBySite)
tabBySite
colnames(tabBySite) <- c("Site", "Status", "N")
reshape(tabBySite, timevar="Status", idvar="Site", direction="wide")
tabBySite <- reshape(tabBySite, timevar="Status", idvar="Site", direction="wide") 
##reorder to put DMD first
tabBySite
tabBySite <- tabBySite[,c(1,3,2)]
##reorder to sort by total numbers
tabBySite <- tabBySite[order(rowSums(as.matrix(tabBySite[,-1])),
                             decreasing=TRUE), ]

##now have a separate table for age
tabByAge <- 
  data.frame(Age = "Age",
             DMD = 
               paste(round(quantile(MasterFrame$Age[MasterFrame$Status == "DMD"],
                                    probs = c(0, 0.5, 1)),1), sep="", collapse=", "),
             Controls = 
               paste(round(quantile(MasterFrame$Age[MasterFrame$Status == "Control"],
                                    probs = c(0, 0.5, 1)),1), sep="", collapse=", "))

tabByAge                                  
##add in total by age categories
tabByAgeGroup <- table(MasterFrame$Category, MasterFrame$Status)
tabByAgeGroup <- data.frame(tabByAgeGroup)
tabByAgeGroup
colnames(tabByAgeGroup) <- c("Age", "Status", "N")
reshape(tabByAgeGroup, timevar="Status", idvar="Age", direction="wide")
tabByAgeGroup <- reshape(tabByAgeGroup, timevar="Status", idvar="Age", direction="wide") 
##reorder to put DMD first
tabByAgeGroup
tabByAgeGroup <- tabByAgeGroup[,c(1,3,2)]
colnames(tabByAge) <- c("Age", "N.DMD", "N.Control")
tabByAge <- sapply(tabByAge, as.character)
tabByAgeGroup <- sapply(tabByAgeGroup, as.character)
tabByAge <- rbind(tabByAge, tabByAgeGroup)
tabByAge

##add in totals at the end
tabByAge <- rbind(tabByAge,
                  c("Total", sum(MasterFrame$Status == "DMD"), 
                    sum(MasterFrame$Status == "Control")))
tabByAge

rownames(tabBySite) <- rownames(tabByAge) <- NULL
@

<<Table1, echo=TRUE, results='asis'>>=
xtable(tabBySite)
xtable(tabByAge)
@

\section{Save objects}

<<saveObj, echo=TRUE>>=
save(list=c("MasterFrame","mets"), file="MasterFrame.RData")
@

\section{Get session info}

Session info:
<<sessInfo, echo=TRUE>>=
sessionInfo()
@

\end{document}